// Code generated by Warden. DO NOT EDIT.

package another

import (
	warden "github.com/egsam98/warden"
	"net/url"
)

func (self *Struct) Validate() error {
	var errs warden.Errors
	if _, err := url.Parse(self.Field); err != nil {
		errs.Add("Field", warden.Error("must be URL"))
	}
	return errs.AsError()
}
